# Generated by Django 5.1.6 on 2025-02-24 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
