# Generated by Django 5.1.6 on 2025-02-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0002_rename_phone_employee_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='nick_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
