# Generated by Django 5.1.6 on 2025-02-24 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0004_alter_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='salons.salon'),
        ),
    ]
