# Generated by Django 5.1.6 on 2025-02-24 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0007_employeedaysoff_employeeworkinghours'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeeworkinghours',
            unique_together={('employee', 'day')},
        ),
    ]
