# Generated by Django 5.1.6 on 2025-02-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0008_alter_employeeworkinghours_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedaysoff',
            old_name='date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='employeedaysoff',
            name='start_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
