# Generated by Django 5.1.6 on 2025-02-28 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0014_alter_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='salons.salon'),
        ),
    ]
