# Generated by Django 5.1.6 on 2025-03-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0015_alter_service_salon'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeworkinghours',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
