# Generated by Django 5.1.6 on 2025-03-14 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0016_employeeworkinghours_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeworkinghours',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='salons.employee'),
        ),
    ]
