# Generated by Django 5.1.6 on 2025-02-24 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookingservice',
            unique_together=set(),
        ),
    ]
