# Generated by Django 5.1.6 on 2025-02-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_bookingservice_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_source',
            field=models.CharField(choices=[('online', 'Online'), ('phone', 'Phone'), ('walk-in', 'Walk-in')], default='online', max_length=20),
        ),
    ]
