# Generated by Django 5.1.6 on 2025-02-27 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_booking_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingservice',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_services', to='bookings.booking'),
        ),
    ]
