# Generated by Django 5.1.6 on 2025-02-28 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_customer'),
        ('salons', '0012_alter_saloncustomer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_customer', to='salons.saloncustomer'),
        ),
    ]
