# Generated by Django 5.1.6 on 2025-02-28 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_alter_booking_customer'),
        ('salons', '0015_alter_service_salon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingservice',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_service', to='salons.service'),
        ),
    ]
