# Generated by Django 5.1.6 on 2025-03-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_alter_bookingservice_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('in_service', 'In Service')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookingservice',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('in_service', 'In Service')], default='scheduled', max_length=20),
        ),
    ]
