# Generated by Django 5.1.6 on 2025-03-14 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_alter_booking_status_alter_bookingservice_status'),
        ('salons', '0016_employeeworkinghours_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingservice',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_employee', to='salons.employee'),
        ),
    ]
